repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
        args: [--single-quote]
        files: \.(js|jsx|ts|tsx|json|md|html|css|scss|yaml)$
  - repo: https://github.com/eslint/eslint
    rev: 'v8.39.0'
    hooks:
      - id: eslint
        args: [--fix]
        files: \.(ts|tsx)$
